### PR TITLE
Coverage option fix

### LINKED ISSUE #31: Code coverage option is not returning coverage
When running lwc-jest with the `--coverage` option no code coverage is returned.

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                   |
----------|----------|----------|----------|----------|-------------------|

### PR DESCRIPTION
**Pull request by muenzpraeger**
Fixes #31

### CODE REVIEW

File: src/config.js [hunk 1]
```diff
@@ -33,8 +34,6 @@ const jestConfig = {
       '<rootDir>/test/specs/',
     ],
     collectCoverageFrom: getCoveragePaths(),
-    // temp workaround until this is released - https://github.com/facebook/jest/pull/6792
-    testURL: "http://localhost/",
```
Comment (trevor-bliss) [inline src/config.js]: Thanks for cleaning this up!
